// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyFridgeApp.Data;

#nullable disable

namespace MyFridgeApp.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20251009060501_AddFridgeLogMigration")]
    partial class AddFridgeLogMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MyFridgeApp.Models.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("MyFridgeApp.Models.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CartId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int?>("ItemId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ItemId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("MyFridgeApp.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "All kinds of meat products",
                            Name = "Meat"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Fish, prawns, and other seafood",
                            Name = "Seafood"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Fresh fruits",
                            Name = "Fruit"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Fresh vegetables",
                            Name = "Vegetable"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Milk, cheese, yogurt, and dairy products",
                            Name = "Dairy"
                        },
                        new
                        {
                            Id = 6,
                            Description = "All types of eggs",
                            Name = "Eggs"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Juices, soft drinks, and other beverages",
                            Name = "Drinks"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Sauces, condiments, and dressings",
                            Name = "Sauces"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Bread, cakes, and other baked goods",
                            Name = "Bakery"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Items not covered by other categories",
                            Name = "Other"
                        });
                });

            modelBuilder.Entity("MyFridgeApp.Models.FridgeLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActionDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LogDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("FridgeLogs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ActionDescription = "Remove Fish Item",
                            LogDate = new DateTime(2025, 10, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            Status = 1
                        },
                        new
                        {
                            Id = 2,
                            ActionDescription = "Add Apple",
                            LogDate = new DateTime(2025, 10, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            Status = 1
                        },
                        new
                        {
                            Id = 3,
                            ActionDescription = "Remove Cabbage",
                            LogDate = new DateTime(2025, 10, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            Status = 1
                        });
                });

            modelBuilder.Entity("MyFridgeApp.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ImportDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            ExpiryDate = new DateTime(2025, 10, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImportDate = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Beef Steak",
                            Notes = "Grass-fed beef",
                            Quantity = 2,
                            Status = 0,
                            Unit = "kg"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            ExpiryDate = new DateTime(2025, 10, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImportDate = new DateTime(2025, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Pork Chops",
                            Notes = "",
                            Quantity = 6,
                            Status = 0,
                            Unit = "pieces"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            ExpiryDate = new DateTime(2025, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImportDate = new DateTime(2025, 9, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Salmon Fillet",
                            Notes = "Fresh Atlantic salmon",
                            Quantity = 1,
                            Status = 0,
                            Unit = "kg"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            ExpiryDate = new DateTime(2025, 10, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImportDate = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Prawns",
                            Notes = "Frozen prawns",
                            Quantity = 500,
                            Status = 0,
                            Unit = "g"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 3,
                            ExpiryDate = new DateTime(2025, 10, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImportDate = new DateTime(2025, 9, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Apples",
                            Notes = "",
                            Quantity = 6,
                            Status = 0,
                            Unit = "pieces"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 3,
                            ExpiryDate = new DateTime(2025, 10, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImportDate = new DateTime(2025, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Bananas",
                            Notes = "Ripe",
                            Quantity = 4,
                            Status = 0,
                            Unit = "pieces"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 3,
                            ExpiryDate = new DateTime(2025, 10, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImportDate = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Grapes",
                            Notes = "Seedless",
                            Quantity = 1,
                            Status = 0,
                            Unit = "kg"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 4,
                            ExpiryDate = new DateTime(2025, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImportDate = new DateTime(2025, 9, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Carrots",
                            Notes = "",
                            Quantity = 1,
                            Status = 0,
                            Unit = "kg"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 4,
                            ExpiryDate = new DateTime(2025, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImportDate = new DateTime(2025, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Broccoli",
                            Notes = "Organic",
                            Quantity = 2,
                            Status = 0,
                            Unit = "pieces"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 5,
                            ExpiryDate = new DateTime(2025, 10, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImportDate = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Milk",
                            Notes = "Low-fat",
                            Quantity = 2,
                            Status = 0,
                            Unit = "liters"
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 5,
                            ExpiryDate = new DateTime(2025, 10, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImportDate = new DateTime(2025, 9, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Cheddar Cheese",
                            Notes = "Block",
                            Quantity = 200,
                            Status = 0,
                            Unit = "g"
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 6,
                            ExpiryDate = new DateTime(2025, 10, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImportDate = new DateTime(2025, 9, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Chicken Eggs",
                            Notes = "Free-range",
                            Quantity = 12,
                            Status = 0,
                            Unit = "pieces"
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 6,
                            ExpiryDate = new DateTime(2025, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImportDate = new DateTime(2025, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Duck Eggs",
                            Notes = "",
                            Quantity = 6,
                            Status = 0,
                            Unit = "pieces"
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 7,
                            ExpiryDate = new DateTime(2025, 10, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImportDate = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Orange Juice",
                            Notes = "Freshly squeezed",
                            Quantity = 1,
                            Status = 0,
                            Unit = "liter"
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 7,
                            ExpiryDate = new DateTime(2026, 4, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImportDate = new DateTime(2025, 9, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Coca-Cola",
                            Notes = "",
                            Quantity = 6,
                            Status = 0,
                            Unit = "cans"
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 8,
                            ExpiryDate = new DateTime(2026, 8, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImportDate = new DateTime(2025, 8, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Tomato Ketchup",
                            Notes = "Big size",
                            Quantity = 1,
                            Status = 0,
                            Unit = "bottle"
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 8,
                            ExpiryDate = new DateTime(2026, 1, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImportDate = new DateTime(2025, 7, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Soy Sauce",
                            Notes = "Japanese style",
                            Quantity = 1,
                            Status = 0,
                            Unit = "bottle"
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 9,
                            ExpiryDate = new DateTime(2025, 10, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImportDate = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Whole Wheat Bread",
                            Notes = "",
                            Quantity = 1,
                            Status = 0,
                            Unit = "loaf"
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 9,
                            ExpiryDate = new DateTime(2025, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImportDate = new DateTime(2025, 10, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Chocolate Cake",
                            Notes = "Birthday cake",
                            Quantity = 1,
                            Status = 0,
                            Unit = "piece"
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 10,
                            ExpiryDate = new DateTime(2025, 10, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImportDate = new DateTime(2025, 9, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Butter",
                            Notes = "Salted",
                            Quantity = 250,
                            Status = 0,
                            Unit = "g"
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 10,
                            ExpiryDate = new DateTime(2026, 3, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImportDate = new DateTime(2025, 9, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Pickles",
                            Notes = "Homemade",
                            Quantity = 1,
                            Status = 0,
                            Unit = "jar"
                        });
                });

            modelBuilder.Entity("MyFridgeApp.Models.CartItem", b =>
                {
                    b.HasOne("MyFridgeApp.Models.Cart", "Cart")
                        .WithMany("Items")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyFridgeApp.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyFridgeApp.Models.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Cart");

                    b.Navigation("Category");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("MyFridgeApp.Models.Item", b =>
                {
                    b.HasOne("MyFridgeApp.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("MyFridgeApp.Models.Cart", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
